### ISSUE TITLE
Very URGENT: SelectByTargetMeanPerformance()  Value Error

### ISSUE THREAD

**Issue by vbabashov** [feature-engine/feature_engine#238] opened 2021-03-15 15:51 UTC
This function throws the following

 **Value Error: Input contains NaN, infinity or a value too large ford type('float64').** None of these seem to be the case.

selector = SelectByTargetMeanPerformance(
    variables=categorical, # the variables to examine
    scoring='r2_score', # the metric to use for the performance evaluation
    threshold=0.1, # the minimum performance threshold for a variable to be selected
    cv=2, # the cross-validation fold
    random_state=0)

selector.fit(X_train, y_train)

Data:

[X_train.xlsx](https://github.com/solegalli/feature_engine/files/6142687/X_train.xlsx)
[y_train.xlsx](https://github.com/solegalli/feature_engine/files/6142688/y_train.xlsx)

Error Snapshot:

[error.pdf](https://github.com/solegalli/feature_engine/files/6142624/error.pdf)

**Comment by solegalli** [comment] 2021-03-15 16:42
Hi @vbabashov 

This error comes up when Nan are introduced automatically when encoding the features with the target mean. There are 2 possible sources that introduce NaN:

1. There are rare categories in the categorical variables, usually, categories in the part of the dataset that is used as test that are not present in the test set
2. The numerical variables are very skewed, so that when they are discretized there are more buckets than values, or values that are not assigned to any bucket.

I recommend finding out which variable is the one with NaN and / or changing the number of bins of numerical variables or removing rare labels in categorical variables before using the transformer.

Hope this helps
Cheers

**Comment by vbabashov** [comment] 2021-03-22 19:09
Thanks for the response. I think it has to do with the 1st point. No success yet! The issue is that there are many features. It's not obvious what variables are causing them. I'm using the Ames, Iowa housing dataset. It's one or more of the features that cause the problem.

**Comment by solegalli** [comment] 2021-03-23 07:31
I add a note here to think how we can improve this transformer to return which variables are causing the problem, and which the problem is.

**Comment by solegalli** [comment] 2021-06-03 12:07
The idea is the following:

Add a catch for error in the MeanEncoder transform method, when the encoding introduces NaN. The error should tell exactly which variables contain NaN after encoding.

In fact, we would add the catch in the BaseEncoder so that it is available to all transformers.

Then we need to somehow provide the user with meaningful error messages in the select by target mean transformer. Need to think the best way forward.

Also, to allow all metrics, we should use cross_validate in the selector

this means that we need to create first a predictor that takes a dataset and returns predictions: mean target value per category or interval.

And then the selector transformer would just take in this predictor and return the cross_validate score.

**Closed** 2022-03-26 08:02 UTC
Labels: code quality, priority
