### ISSUE TITLE
Don't error when DropFeatures get's empty list

### ISSUE THREAD

**Issue by sTomerG** [feature-engine/feature_engine#567] opened 2022-11-23 11:22 UTC
**Is your feature request related to a problem? Please describe.**
To be able to more easily gridsearch over which features to drop using `DropFeatures` it would be helpful if `DropFeatures` wouldn't generate a `ValueError` when `len(features_to_drop) == 0`, so that you can also choose to not drop any features in the gridsearch by inserting an empty list as value.

**Describe the solution you'd like**
remove `or len(features_to_drop) == 0` from line 58 in _drop_features.py_

**Describe alternatives you've considered**
Forking the library and removing the line of code myself (which I already did), but I might think this improvement could help other people as well.

**Comment by solegalli** [comment] 2022-11-23 15:27
Hi @sTomerG 

Thanks for the suggestion. This is a use of `DropFeatures` that I had not thought of :)

Going back to my thinking when I designed this class: it was intended for users to remove features based on some domain knowledge. Thus, calling this class and removing no feature (empty list) made no sense. Hence, the error check.

Of course I did not see the potential use in combination with GridSearch.

To try and understand how common this would be, could you explain a bit more of the scenario in which you use it together with a gridsearch? I guess you try different feature combinations, plus the empty list. Why would you enter different feature combinations manually?

Re the code change: I'd say, if you already created a solution (removing the check + test), then go ahead and make a PR.

**Comment by sTomerG** [comment] 2022-11-24 09:40
Thanks for your quick reply @solegalli :). Now that I've thought about it some more; this actually applies to more classes in feature-engine which have a parameter that specifies on which variables the transformation should be applied.

With categorical encoding, you might want to gridsearch whether the model learns more of the feature through ordinal encoding or through mean encoding. This would be possible if the parameter`variables` could be set to an empty list without generating an error (now it generates `ValueError: list of variables is empty.`), so that you could e.g. create a GridSearch with:

```
{
    [
          (...)
        "(...)__meanencoder__variables": [ ["country"] ],
        "(...)__ordinalencoder__variables": [ [] ],
         (...)
    ],
    [
         (...)
        "(...)__meanencoder__variables": [ [] ],
        "(...)__ordinalencoder__variables": [ ["country"] ],
         (...)
    ],
}
```

This would result in `variables` taking:
`None` -> transform automatically chosen variables based on their data type
`str | List[str]` (etc) -> transform specified variables
`[]` -> don't transform variables

To me, this feels like it makes sense because variables are "_The list of categorical variables that will be encoded."_, hence: empty list, no variables encoded.

**Comment by solegalli** [comment] 2022-11-24 10:11
I see the point for automation. But I also think that removing the "safety net" of alerting the user when no variables will be transformed by the encoder is too dangerous, i.e., the user may think that their variables are being transformed, but they are not.

There could be options with Optuna to sample the param space with no variables. Optuna allows to define parameters with the define-by-run method. If you have a real code example, we could try to figure out how to do it, and then maybe create some example in the documentation for others to look at.

**Comment by sTomerG** [comment] 2022-11-29 12:53
Hi! 

I've found a solution; I've created a meta-estimator which can turn other estimators/transformers in a Pipeline on or off :)
```
class EstimatorSwitch(TransformerMixin, BaseEstimator):
    """A Meta Estimator that can turn on or off an estimator \
        in a scikit-learn Pipeline.

    Parameters
    ----------
    estimator : Any
        The estimator to turn on or off.
    apply : bool
        To apply the estimator, by default True.
        
    Examples
    --------
    >>> import numpy as np
    >>> from sklearn.pipeline import make_pipeline
    >>> from sklearn.impute import SimpleImputer, MissingIndicator
    >>> from extra_ds_tools.ml.sklearn.meta_estimators import EstimatorSwitch
    >>> X = np.array([np.nan, 10] * 2).reshape(-1, 1)
    >>> # The SimpleImputer should transform the nans to the mean, which is 10.
    >>> pipeline = make_pipeline(EstimatorSwitch(SimpleImputer(), apply=False))
    >>> print(pipeline.fit_transform(X))
    [[nan]
    [10.]
    [nan]
    [10.]]
    """  # noqa

    def __init__(self, estimator: Any, *, apply: bool = True):
        self.estimator = estimator
        self.apply = apply

    def fit(
        self,
        X: Union[pd.DataFrame, pd.Series, np.array],
        y: Optional[Union[pd.Series, np.array]] = None,
        **fit_params
    ):
        """Fits the estimator on the data if self.apply == True.

        Parameters
        ----------
        X : Union[pd.DataFrame, pd.Series, np.array]
            Train data.
        y : Optional[Union[pd.Series, np.array]], optional
            Target data, by default None.

        Returns
        -------
        EstimatorSwitch
            EstimatorSwitch with a fitted estimator if self.apply == True.
        """
        if self.apply:
            return self.estimator.fit(X, y, **fit_params)
        return self

    def transform(
        self,
        X: Union[pd.DataFrame, pd.Series, np.array],
        y: Optional[Union[pd.Series, np.array]] = None,
        **fit_params
    ):
        """Returns the transformed X if self.apply == True.

        Parameters
        ----------
         X : Union[pd.DataFrame, pd.Series, np.array]
             Train data.
         y : Optional[Union[pd.Series, np.array]], optional
             Target data, by default None.

        Returns
        -------
        Union[pd.DataFrame, pd.Series, np.array]
             Transformed X.
        """
        if self.apply:
            return self.estimator.transform(X, y, **fit_params)
        return X
```

**Comment by solegalli** [comment] 2022-12-07 10:24
I guess this is resolved now, so I am closing this issue. Thanks for sharing your implementation and solution @sTomerG

**Closed by solegalli** 2022-12-07 10:24 UTC

**Comment by sTomerG** [comment] 2022-12-07 13:48
Yes closing is fine! @solegalli  If you're interested, in [this article](https://medium.com/towards-data-science/significantly-increase-your-grid-search-results-with-these-parameters-b096b3d158aa) I've explained strategies on how to use feature-engine's transformers in a grid search :)

**Comment by solegalli** [comment] 2022-12-08 09:16
Thank you @sTomerG ! I shared on social :p
